# Generated by Django 4.2.2 on 2023-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(),
        ),
    ]
