# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161101_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='num_cols',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '6')], default='2', max_length=2, verbose_name='number columns'),
        ),
    ]
