# Generated by Django 2.0.6 on 2018-06-16 19:43

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='location')),
                ('mark_used', models.BooleanField(default=True, verbose_name='mark used')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='events.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'access control point',
                'verbose_name_plural': 'access control points',
            },
        ),
        migrations.CreateModel(
            name='LogAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('wrong', 'wrong'), ('incorrect', 'incorrect'), ('used', 'used'), ('maybe', 'maybe')], default='ok', max_length=10, verbose_name='status')),
                ('access_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_access', to='access.AccessControl', verbose_name='access control')),
            ],
            options={
                'verbose_name': 'access control point log',
                'verbose_name_plural': 'access control point logs',
            },
        ),
    ]
