# Generated by Django 2.0.6 on 2018-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
