# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('access_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_access', to='access.AccessControl')),
            ],
        ),
    ]
