# Generated by Django 2.2.28 on 2022-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20181113_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('right', 'ok'), ('wrong', 'wrong'), ('incorrect', 'incorrect'), ('used', 'used'), ('maybe', 'maybe')], default='right', max_length=10, verbose_name='status'),
        ),
    ]
