# Generated by Django 2.2.28 on 2022-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20221004_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('wrong', 'wrong'), ('incorrect', 'incorrect'), ('used', 'used'), ('maybe', 'maybe')], default='ok', max_length=10, verbose_name='status'),
        ),
    ]
