# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_logaccesscontrol_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'verbose_name': 'access control point', 'verbose_name_plural': 'access control points'},
        ),
        migrations.AlterModelOptions(
            name='logaccesscontrol',
            options={'verbose_name': 'access control point log', 'verbose_name_plural': 'access control point logs'},
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('wrong', 'wrong'), ('used', 'used'), ('maybe', 'maybe')], default='ok', max_length=10, verbose_name='status'),
        ),
    ]
