# Generated by Django 4.2.2 on 2023-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20221004_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('right', 'ok'), ('wrong', 'wrong'), ('incorrect', 'incorrect'), ('used', 'used'), ('maybe', 'maybe')], default='right', max_length=10, verbose_name='status'),
        ),
    ]
