# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20160712_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='access_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_access', to='access.AccessControl', verbose_name='access control'),
        ),
    ]
