# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20160712_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='mark_used',
            field=models.BooleanField(default=True, verbose_name='mark used'),
        ),
    ]
