# Generated by Django 4.2.5 on 2023-10-31 11:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_accesscontrol_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accesscontrol',
            managers=[
                ('read_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
