# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_accesscontrol_mark_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaccesscontrol',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('wrong', 'wrong'), ('incorrect', 'incorrect'), ('used', 'used'), ('maybe', 'maybe')], default='ok', max_length=10, verbose_name='status'),
        ),
    ]
