# Generated by Django 4.2.5 on 2023-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_accesscontrol_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='read_inv',
            field=models.BooleanField(default=True, verbose_name='read invitations'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='read_mp',
            field=models.BooleanField(default=True, verbose_name='read multipurchases'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='read_tickets',
            field=models.BooleanField(default=True, verbose_name='read tickets'),
        ),
    ]
