# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0027_session_autoseat_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, unique=True, verbose_name='order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='extra data')),
                ('is_pass', models.BooleanField(default=False, verbose_name='is pass')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('used_date', models.DateTimeField(blank=True, null=True, verbose_name='invitation used date')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
            bases=(models.Model, tickets.models.BaseExtraData),
        ),
        migrations.CreateModel(
            name='InvitationGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='amount')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('concept', models.CharField(max_length=200, verbose_name='concept')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'invitation generator',
                'verbose_name_plural': 'invitation generators',
            },
        ),
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_pass', models.BooleanField(default=False, verbose_name='is pass')),
                ('start', models.DateTimeField(null=True, verbose_name='start date')),
                ('end', models.DateTimeField(null=True, verbose_name='end date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_types', to='events.Event', verbose_name='event')),
                ('gates', models.ManyToManyField(blank=True, null=True, to='events.Gate', verbose_name='gates')),
                ('sessions', models.ManyToManyField(blank=True, null=True, related_name='invitation_types', to='events.Session', verbose_name='sessions')),
            ],
            options={
                'verbose_name': 'invitation type',
                'verbose_name_plural': 'invitation types',
            },
        ),
        migrations.AddField(
            model_name='invitationgenerator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invs.InvitationType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invs.InvitationGenerator', verbose_name='generator'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invs.InvitationType', verbose_name='invitation type'),
        ),
    ]
