# Generated by Django 2.0.6 on 2018-06-16 19:44

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, unique=True, verbose_name='order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='extra data')),
                ('is_pass', models.BooleanField(default=False, verbose_name='is pass')),
                ('seat', models.CharField(blank=True, max_length=20, null=True, verbose_name='seat')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
            bases=(models.Model, tickets.models.BaseExtraData),
        ),
        migrations.CreateModel(
            name='InvitationGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='amount')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('tax', models.IntegerField(null=True, verbose_name='tax')),
                ('concept', models.CharField(max_length=200, verbose_name='concept')),
                ('seats', models.CharField(blank=True, help_text='C1[1-1,1-3]; C2[2-1:2-4]', max_length=1024, null=True, verbose_name='seats')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'invitation generator',
                'verbose_name_plural': 'invitation generators',
            },
        ),
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_pass', models.BooleanField(default=False, verbose_name='is pass')),
                ('one_time_for_session', models.BooleanField(default=False, help_text='This is used for passes that will be only valid one time for each session. Invitations always have only one use. So this is ignored in invitations.', verbose_name='one time for session')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_types', to='events.Event', verbose_name='event')),
                ('gates', models.ManyToManyField(blank=True, to='events.Gate', verbose_name='gates')),
                ('sessions', models.ManyToManyField(blank=True, related_name='invitation_types', to='events.Session', verbose_name='sessions')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.TicketTemplate', verbose_name='template')),
                ('thermal_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ThermalTicketTemplate', verbose_name='thermal template')),
            ],
            options={
                'verbose_name': 'invitation type',
                'verbose_name_plural': 'invitation types',
                'ordering': ['-event__name'],
            },
        ),
        migrations.CreateModel(
            name='InvUsedInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedin', to='invs.Invitation', verbose_name='invitation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedby', to='events.Session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'invitation used in',
                'verbose_name_plural': 'invitations used in',
            },
        ),
        migrations.AddField(
            model_name='invitationgenerator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invs.InvitationType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invs.InvitationGenerator', verbose_name='generator'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout', verbose_name='seat layout'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invs.InvitationType', verbose_name='invitation type'),
        ),
    ]
