# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtype',
            name='gates',
            field=models.ManyToManyField(blank=True, to='events.Gate', verbose_name='gates'),
        ),
        migrations.AlterField(
            model_name='invitationtype',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='invitation_types', to='events.Session', verbose_name='sessions'),
        ),
    ]
