# Generated by Django 2.0.13 on 2019-11-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationgenerator',
            options={'ordering': ('-created',), 'verbose_name': 'invitation generator', 'verbose_name_plural': 'invitation generators'},
        ),
        migrations.AlterModelOptions(
            name='invitationtype',
            options={'ordering': ('-event__name', 'name'), 'verbose_name': 'invitation type', 'verbose_name_plural': 'invitation types'},
        ),
    ]
