# Generated by Django 2.2.24 on 2021-09-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0002_auto_20191123_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationtype',
            name='thermal_template',
        ),
        migrations.AlterField(
            model_name='invitationtype',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.TicketTemplate', verbose_name='template'),
            preserve_default=False,
        ),
    ]
