# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0002_auto_20160811_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtype',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='invitationtype',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
