# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0003_auto_20160811_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationgenerator',
            name='tax',
            field=models.IntegerField(null=True, verbose_name='tax'),
        ),
    ]
