# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20160813_1138'),
        ('invs', '0004_invitationgenerator_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='seat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='seat'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout', verbose_name='seat layout'),
        ),
    ]
