# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_session_dateformat'),
        ('invs', '0007_auto_20161028_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvUsedInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'invitations used in',
                'verbose_name': 'invitation used in',
            },
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='used',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='used_date',
        ),
        migrations.AddField(
            model_name='invitationtype',
            name='one_time_for_session',
            field=models.BooleanField(default=False, verbose_name='one time for session'),
        ),
        migrations.AddField(
            model_name='invusedinsession',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedin', to='invs.Invitation', verbose_name='invitation'),
        ),
        migrations.AddField(
            model_name='invusedinsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedby', to='events.Session', verbose_name='session'),
        ),
    ]
