# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(upload_to='attachments', verbose_name='attach')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachs', to='events.ConfirmEmail')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('price', models.IntegerField(default=25, verbose_name='ticket price')),
                ('price_student', models.IntegerField(default=25, verbose_name='student price')),
                ('price_speaker', models.IntegerField(default=0, verbose_name='speaker price')),
                ('price_invited', models.IntegerField(default=0, verbose_name='invited price')),
                ('info', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('admin', models.EmailField(blank=True, max_length=254, null=True, verbose_name='admin email')),
                ('max', models.IntegerField(default=300, verbose_name='max tickets')),
                ('tshirt_img', models.ImageField(blank=True, null=True, upload_to='tshirts', verbose_name='t-shirt img')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='InvCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='code')),
                ('person', models.CharField(blank=True, max_length=100, null=True, verbose_name='for person')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('type', models.CharField(choices=[('invited', 'Invited'), ('speaker', 'Speaker'), ('student', 'Student')], default='invited', max_length=15, verbose_name='type')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='confirmemail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='events.Event'),
        ),
    ]
