# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('capacity', models.IntegerField(default=100, verbose_name='capacity')),
                ('numbered', models.BooleanField(default=False, verbose_name='numbered')),
                ('layout', models.TextField(blank=True, help_text='the layout to select the numbered seat', null=True, verbose_name='seats layout')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='events.Event')),
            ],
        ),
    ]
