# Generated by Django 2.0.6 on 2018-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180703_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sale_enabled',
            field=models.BooleanField(default=True, verbose_name='sale enabled'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_sale_message',
            field=models.TextField(blank=True, help_text='Message to show when the ticket sale is disabled', null=True, verbose_name='sale message'),
        ),
    ]
