# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160428_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'TextArea'), ('check', 'CheckBox'), ('select', 'Select')], default='text', max_length=100)),
                ('options', models.CharField(blank=True, help_text='comma separated values, only for select type', max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_invited',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_speaker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_student',
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.Event'),
        ),
    ]
