# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160429_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='label',
            field=models.CharField(default='label', max_length=100, verbose_name='label'),
            preserve_default=False,
        ),
    ]
