# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:33
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160429_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
