# Generated by Django 2.0.13 on 2021-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_session_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='bottom_margin',
            field=models.FloatField(default=2.54, help_text='in cm', verbose_name='bottom margin'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='left_margin',
            field=models.FloatField(default=2.54, help_text='in cm', verbose_name='left margin'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='pagesize_height',
            field=models.FloatField(default=24.62, help_text='in cm', verbose_name='pagesize height'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='pagesize_width',
            field=models.FloatField(default=15.92, help_text='in cm', verbose_name='pagesize width'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='right_margin',
            field=models.FloatField(default=2.54, help_text='in cm', verbose_name='right margin'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='top_margin',
            field=models.FloatField(default=2.54, help_text='in cm', verbose_name='top margin'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='contributors',
            field=models.ImageField(blank=True, null=True, upload_to='templcontributors', verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='info',
            field=models.TextField(blank=True, help_text='change fontsize: &ltfont size=6&gtNOTE&lt/font&gt</br>bold: &ltb&gtNOTE&lt/b&gt', null=True, verbose_name='next note'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='previous note'),
        ),
    ]
