# Generated by Django 2.2.24 on 2021-09-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invs', '0003_auto_20210903_1044'),
        ('events', '0006_auto_20210820_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='thermal_template',
        ),
        migrations.AlterField(
            model_name='session',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.TicketTemplate', verbose_name='template'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ThermalTicketTemplate',
        ),
    ]
