# Generated by Django 2.2.24 on 2021-10-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210903_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='border_qr',
            field=models.FloatField(default=0, verbose_name='border qr'),
        ),
    ]
