# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_tshirt_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
