# Generated by Django 2.2.28 on 2022-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220930_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='extra_js',
            field=models.TextField(blank=True, help_text='Extra js for configure template', null=True, verbose_name='extra js'),
        ),
    ]
