# Generated by Django 2.2.28 on 2022-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_tickettemplate_extra_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='is_html_format',
            field=models.BooleanField(default=False, verbose_name='is html format'),
        ),
    ]
