# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160513_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='seat_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='events.SeatMap'),
        ),
    ]
