# Generated by Django 4.2.2 on 2023-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_space_description_space_foot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, default='', help_text='Campo en html que se mostrará en la página de inicio', verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Igual que el campo título, aunque como el css lo añadimos nosotros, la clase la tendremos que crear nosotros.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='foot_description',
            field=models.TextField(blank=True, default='', help_text='Igual que la descripción', verbose_name='foot description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.TextField(default='', help_text="Por defecto, el título se mostrará sin estilos, si queremos aplicar algún estilo al título, tendremos que hacerlo desde el panel de administración, en theme --> theme config --> custom css, usando la class 'title'", verbose_name='title'),
        ),
    ]
