# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20160523_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start']},
        ),
    ]
