# Generated by Django 4.2.2 on 2023-09-09 19:46

from django.db import migrations, models
import django.db.models.deletion


def copy_template(apps, schema_editor):
    Session = apps.get_model("events", "Session")
    for session in Session.objects.all():
        session.window_template = session.template
        session.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_event_info_alter_space_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="window_template",
            field=models.ForeignKey(
                default=None,
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="window_templates",
                to="events.tickettemplate",
                verbose_name="window template",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.tickettemplate",
                verbose_name="template",
            ),
        ),
        migrations.RunPython(copy_template),
    ]
