# Generated by Django 4.2.2 on 2023-09-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_session_window_template_alter_session_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='window_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='window_templates', to='events.tickettemplate', verbose_name='window template'),
        ),
    ]
