# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20160526_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
