# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_space_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['order']},
        ),
    ]
