# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20160608_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='window_price',
            field=models.IntegerField(default=10, verbose_name='price in the ticket window'),
        ),
    ]
