# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_session_window_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='seatlayout',
            name='column_start_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seatlayout',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Gate'),
        ),
    ]
