# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_tickettemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.TicketTemplate'),
        ),
    ]
