# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_session_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemail',
            options={'verbose_name': 'confirm email', 'verbose_name_plural': 'confirm emails'},
        ),
        migrations.AlterModelOptions(
            name='emailattachment',
            options={'verbose_name': 'email attachment', 'verbose_name_plural': 'email attachments'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='extrasession',
            options={'verbose_name': 'extra session', 'verbose_name_plural': 'extra sessions'},
        ),
        migrations.AlterModelOptions(
            name='gate',
            options={'verbose_name': 'gate', 'verbose_name_plural': 'gates'},
        ),
        migrations.AlterModelOptions(
            name='invcode',
            options={'verbose_name': 'invitation code', 'verbose_name_plural': 'invitation codes'},
        ),
        migrations.AlterModelOptions(
            name='seatlayout',
            options={'verbose_name': 'seat Layout', 'verbose_name_plural': 'seat Layouts'},
        ),
        migrations.AlterModelOptions(
            name='seatmap',
            options={'verbose_name': 'seat Map', 'verbose_name_plural': 'seat Maps'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['order'], 'verbose_name': 'space', 'verbose_name_plural': 'spaces'},
        ),
        migrations.AlterModelOptions(
            name='ticketfield',
            options={'ordering': ['order'], 'verbose_name': 'ticket field', 'verbose_name_plural': 'ticket fields'},
        ),
        migrations.AlterModelOptions(
            name='tickettemplate',
            options={'verbose_name': 'ticket template', 'verbose_name_plural': 'ticket templates'},
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='extrasession',
            name='used',
            field=models.BooleanField(default=False, verbose_name='used'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='column_start_number',
            field=models.IntegerField(default=1, verbose_name='column start number'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='direction',
            field=models.CharField(choices=[('u', 'Up'), ('l', 'Left'), ('r', 'Right'), ('d', 'Down')], default='d', max_length=2, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='left',
            field=models.IntegerField(default=0, verbose_name='left'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='top',
            field=models.IntegerField(default=0, verbose_name='top'),
        ),
        migrations.AlterField(
            model_name='seatmap',
            name='scene_bottom',
            field=models.IntegerField(default=0, verbose_name='scene bottom limit'),
        ),
        migrations.AlterField(
            model_name='seatmap',
            name='scene_left',
            field=models.IntegerField(default=0, verbose_name='scene left limit'),
        ),
        migrations.AlterField(
            model_name='seatmap',
            name='scene_right',
            field=models.IntegerField(default=0, verbose_name='scene right limit'),
        ),
        migrations.AlterField(
            model_name='seatmap',
            name='scene_top',
            field=models.IntegerField(default=0, verbose_name='scene top limit'),
        ),
        migrations.AlterField(
            model_name='space',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='options',
            field=models.CharField(blank=True, help_text='comma separated values, only for select type', max_length=500, null=True, verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'TextArea'), ('check', 'CheckBox'), ('select', 'Select')], default='text', max_length=100, verbose_name='type'),
        ),
    ]
