# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20160712_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachs', to='events.ConfirmEmail', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='extrasession',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_sessions', to='events.Session', verbose_name='extra'),
        ),
        migrations.AlterField(
            model_name='extrasession',
            name='orig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_sessions', to='events.Session', verbose_name='orig'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='invcode',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Gate', verbose_name='gate'),
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='events.SeatMap', verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='session',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.Space', verbose_name='space'),
        ),
        migrations.AlterField(
            model_name='session',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.TicketTemplate', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='space',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='space',
            name='seat_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='events.SeatMap', verbose_name='seat map'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.Event', verbose_name='event'),
        ),
    ]
