# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20160712_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlayout',
            name='layout',
            field=models.TextField(help_text='the layout to select the numbered seat. L = Free, _ = Space, R = Reserved', verbose_name='seats layout'),
        ),
    ]
