# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20160712_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfield',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('tel', 'Phone'), ('url', 'URL'), ('text', 'Text'), ('textarea', 'TextArea'), ('check', 'CheckBox'), ('select', 'Select')], default='text', max_length=100, verbose_name='type'),
        ),
    ]
