# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20160721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='autoseat_mode',
            field=models.CharField(default='ASC', help_text='ASC, DESC, RANDOM or LIST: layout_name1,layout_name2', max_length=300, verbose_name='autoseat mode'),
        ),
    ]
