# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_session_autoseat_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=8, verbose_name='type')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Discount', verbose_name='discounts'),
        ),
    ]
