# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20160813_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='label',
            field=models.CharField(max_length=300, verbose_name='label'),
        ),
    ]
