# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20160831_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfield',
            name='label',
            field=models.CharField(max_length=500, verbose_name='label'),
        ),
    ]
