# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_tickettemplate_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.FloatField(default=10, verbose_name='ticket price'),
        ),
        migrations.AlterField(
            model_name='session',
            name='window_price',
            field=models.FloatField(default=10, verbose_name='price in the ticket window'),
        ),
    ]
