# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20160916_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='short name'),
        ),
    ]
