# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_session_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalTicketTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('header', models.ImageField(blank=True, null=True, upload_to='templheader', verbose_name='header')),
                ('sponsors', models.ImageField(blank=True, null=True, upload_to='templsponsors', verbose_name='sponsors')),
                ('background', models.ImageField(blank=True, null=True, upload_to='templsback', verbose_name='background')),
                ('width', models.IntegerField(default=1795, verbose_name='width')),
                ('height', models.IntegerField(default=815, verbose_name='height')),
            ],
            options={
                'verbose_name_plural': 'thermal ticket templates',
                'verbose_name': 'thermal ticket template',
            },
        ),
    ]
