# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_thermaltickettemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='thermal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ThermalTicketTemplate', verbose_name='thermal template'),
        ),
    ]
