# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_discount_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='dateformat',
            field=models.CharField(choices=[('start', 'Date and start time'), ('complete', 'Date, start and end time'), ('onlydate', 'Only date')], default='start', max_length=50, verbose_name='date format'),
        ),
    ]
