# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_event_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'xl')], default='M', max_length=3, verbose_name='size')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tshirt', to='tickets.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tshirt_img',
            field=models.ImageField(blank=True, null=True, upload_to='tshirts', verbose_name='t-shirt img'),
        ),
    ]
