# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20160427_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='event',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='food',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='org',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
