# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160429_1111'),
        ('tickets', '0026_auto_20160504_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipurchase',
            name='ev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='events.Event'),
            preserve_default=False,
        ),
    ]
