# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_multipurchase_ev'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='session_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='space_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
