# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160513_1024'),
        ('tickets', '0028_auto_20160511_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('session', models.ManyToManyField(related_name='warnings', to='events.Session')),
            ],
        ),
    ]
