# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticketwarning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketwarning',
            old_name='session',
            new_name='sessions',
        ),
    ]
