# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160513_1024'),
        ('tickets', '0031_ticketwarning_ev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketwarning',
            name='sessions',
        ),
        migrations.AddField(
            model_name='ticketwarning',
            name='sessions1',
            field=models.ManyToManyField(related_name='warnings1', to='events.Session'),
        ),
        migrations.AddField(
            model_name='ticketwarning',
            name='sessions2',
            field=models.ManyToManyField(related_name='warnings2', to='events.Session'),
        ),
        migrations.AddField(
            model_name='ticketwarning',
            name='type',
            field=models.CharField(choices=[('and', 'AND'), ('or', 'OR'), ('2req1', 'Second required first')], default='and', max_length=10),
        ),
    ]
