# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_auto_20160518_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketwarning',
            name='type',
            field=models.CharField(choices=[('req', 'Required')], default='req', max_length=10),
        ),
    ]
