# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_auto_20160518_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout'),
        ),
    ]
