# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ticketseathold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
