# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_ticket_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold_in_window',
            field=models.BooleanField(default=False),
        ),
    ]
