# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20160616_1936'),
        ('tickets', '0040_ticket_gate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, unique=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('seat', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('ina', 'Inauguration Invitation'), ('mad', 'MaD Facility Invitation'), ('thu', 'Thursday Show Invitation')], default='mad', max_length=3)),
                ('used', models.BooleanField(default=False)),
                ('seat_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, unique=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('seat', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('org', 'Organization Pass'), ('vip', 'Vip Pass'), ('par', 'Rancher Partner Pass'), ('sym', 'Sympathizer Pass'), ('exh', 'Exhibitor Pass'), ('pre', 'Press Pass'), ('jur', 'Jury Pass')], default='vip', max_length=3)),
                ('used', models.BooleanField(default=False)),
                ('seat_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout')),
            ],
        ),
    ]
