# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_invitation_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField(null=True, verbose_name='start date')),
                ('end', models.DateTimeField(null=True, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField(null=True, verbose_name='start date')),
                ('end', models.DateTimeField(null=True, verbose_name='end date')),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.InvitationType'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.PassType'),
        ),
    ]
