# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_session_template'),
        ('tickets', '0042_auto_20160623_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.Session'),
        ),
        migrations.AddField(
            model_name='pass',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='events.Session'),
        ),
    ]
