# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_session_template'),
        ('tickets', '0043_auto_20160623_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtype',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_types', to='events.Session'),
        ),
        migrations.AddField(
            model_name='passtype',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_types', to='events.Session'),
        ),
    ]
