# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_auto_20160623_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='seat_layout',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='session',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='type',
        ),
        migrations.RemoveField(
            model_name='passtype',
            name='session',
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.DeleteModel(
            name='PassType',
        ),
    ]
