# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_auto_20160711_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'invitation', 'verbose_name_plural': 'invitations'},
        ),
        migrations.AlterModelOptions(
            name='invitationtype',
            options={'verbose_name': 'invitation type', 'verbose_name_plural': 'invitation types'},
        ),
        migrations.AlterModelOptions(
            name='multipurchase',
            options={'ordering': ['-created'], 'verbose_name': 'multipurchase', 'verbose_name_plural': 'multipurchases'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketseathold',
            options={'verbose_name': 'ticket seat hold', 'verbose_name_plural': 'ticket seat holds'},
        ),
        migrations.AlterModelOptions(
            name='ticketwarning',
            options={'verbose_name': 'ticket warning', 'verbose_name_plural': 'ticket warnings'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='is pass'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='order',
            field=models.CharField(max_length=200, unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='seat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='seat'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(default=False, verbose_name='used'),
        ),
        migrations.AlterField(
            model_name='invitationtype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='confirm_sent',
            field=models.BooleanField(default=False, verbose_name='confirmation sent'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='order',
            field=models.CharField(max_length=200, unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='order_tpv',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='order TPV'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='confirm_sent',
            field=models.BooleanField(default=False, verbose_name='confirmation sent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='event name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gate_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='gate name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.CharField(max_length=200, unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_tpv',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='order TPV'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_layout_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='seat layout name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='session name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sold_in_window',
            field=models.BooleanField(default=False, verbose_name='sold in window'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='space_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='space name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tax',
            field=models.IntegerField(null=True, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=False, verbose_name='used'),
        ),
        migrations.AlterField(
            model_name='ticketseathold',
            name='client',
            field=models.CharField(max_length=20, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='ticketseathold',
            name='seat',
            field=models.CharField(help_text='row-col', max_length=20, verbose_name='seat'),
        ),
        migrations.AlterField(
            model_name='ticketwarning',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='ticketwarning',
            name='type',
            field=models.CharField(choices=[('req', 'Required')], default='req', max_length=10, verbose_name='type'),
        ),
    ]
