# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_auto_20160712_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout', verbose_name='seat layout'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.Session', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.InvitationType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='invitationtype',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_types', to='events.Session', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='multipurchase',
            name='ev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.InvCode', verbose_name='invitation code'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.MultiPurchase', verbose_name='multipurchase'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout', verbose_name='seat layout'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.Session', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='ticketseathold',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SeatLayout', verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='ticketseathold',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='events.Session', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='ticketwarning',
            name='ev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='ticketwarning',
            name='sessions1',
            field=models.ManyToManyField(related_name='warnings1', to='events.Session', verbose_name='sessions1'),
        ),
        migrations.AlterField(
            model_name='ticketwarning',
            name='sessions2',
            field=models.ManyToManyField(related_name='warnings2', to='events.Session', verbose_name='sessions2'),
        ),
    ]
