# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_auto_20160712_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ticket used date'),
        ),
    ]
