# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_auto_20160729_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_pass',
        ),
        migrations.AddField(
            model_name='invitationtype',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='is pass'),
        ),
        migrations.AlterField(
            model_name='invitationgenerator',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
