# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_auto_20160729_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationgenerator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.InvitationType', verbose_name='type'),
        ),
    ]
