# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_auto_20160730_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='seat_layout',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='session',
        ),
        migrations.RemoveField(
            model_name='invitationgenerator',
            name='type',
        ),
        migrations.RemoveField(
            model_name='invitationtype',
            name='session',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='InvitationGenerator',
        ),
        migrations.DeleteModel(
            name='InvitationType',
        ),
    ]
