# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20160813_1138'),
        ('tickets', '0052_auto_20160811_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipurchase',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='events.Discount', verbose_name='discount'),
        ),
    ]
