# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_multipurchase_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketseathold',
            name='type',
            field=models.CharField(choices=[('H', 'Holded'), ('C', 'Confirming'), ('R', 'Reserved')], default='H', max_length=2, verbose_name='type'),
        ),
    ]
