# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_auto_20160825_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipurchase',
            name='tpv_error',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='error TPV'),
        ),
        migrations.AddField(
            model_name='multipurchase',
            name='tpv_error_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='error TPV info'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tpv_error',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='error TPV'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tpv_error_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='error TPV info'),
        ),
    ]
