# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0056_auto_20160913_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
