# Generated by Django 2.0.6 on 2018-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='singlerow',
            field=models.BooleanField(default=False, verbose_name='single row'),
        ),
    ]
