# Generated by Django 2.0.6 on 2018-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0005_ticketwindow_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='print_close_timeout',
            field=models.FloatField(default=1.0, help_text='Time to auto close the ticket PDF popup window, use 0 to disable auto close', verbose_name='PDF ticket window close timeout'),
        ),
    ]
