# Generated by Django 2.0.6 on 2018-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0007_ticketwindow_shortcuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='autocall_singlerow',
            field=models.BooleanField(default=True, verbose_name='autocall singlerow'),
        ),
    ]
