# Generated by Django 4.2.2 on 2023-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_tickettemplate_extra_html_alter_event_slug_and_more'),
        ('windows', '0009_ticketwindow_number_of_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='templates',
            field=models.ManyToManyField(to='events.tickettemplate'),
        ),
        migrations.AlterField(
            model_name='ticketwindow',
            name='shortcuts',
            field=models.JSONField(default={'add': 145, 'onoff': 42, 'sub': 19}),
        ),
        migrations.AlterField(
            model_name='ticketwindow',
            name='slug',
            field=models.SlugField(),
        ),
    ]
