# Generated by Django 4.2.2 on 2023-09-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0010_ticketwindow_templates_alter_ticketwindow_shortcuts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketwindow',
            name='templates',
        ),
    ]
