# Generated by Django 2.0.6 on 2018-08-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_auto_20180718_0903'),
        ('windows', '0002_ticketwindow_singlerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleRowTail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_row_tail', to='events.Event', verbose_name='event')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_row_tail', to='windows.TicketWindow', verbose_name='window')),
            ],
        ),
    ]
