# Generated by Django 2.0.6 on 2018-08-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlerow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlerowtail',
            options={'ordering': ['date']},
        ),
    ]
