# Generated by Django 2.0.6 on 2018-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlerow', '0003_auto_20181030_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerowconfig',
            name='say_direction',
            field=models.BooleanField(default=True, verbose_name='say direction'),
        ),
        migrations.AlterField(
            model_name='singlerowconfig',
            name='extra_text',
            field=models.TextField(blank=True, null=True, verbose_name='extra text'),
        ),
    ]
