# Generated by Django 2.0.6 on 2018-10-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_ticketwindow_singlerow_pos'),
        ('singlerow', '0004_auto_20181030_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerowconfig',
            name='last_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windows.TicketWindow', verbose_name='last ticket window'),
        ),
    ]
