# Generated by Django 2.0.6 on 2018-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlerow', '0006_auto_20181030_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerowconfig',
            name='logo',
            field=models.CharField(default='', max_length=1024, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='singlerowconfig',
            name='video',
            field=models.CharField(default='', max_length=1024, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='singlerowconfig',
            name='waiting',
            field=models.ManyToManyField(blank=True, related_name='config_waiting', to='windows.TicketWindow', verbose_name='waiting ticket windows'),
        ),
    ]
