# Generated by Django 2.0.6 on 2018-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0002_ticketwindow_singlerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='supplement',
            field=models.FloatField(default=0, verbose_name='increments or decrements the ticket price for this window'),
        ),
    ]
