# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 16:19
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.models import Group


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'fixtures/groups.json')

def unload_fixture(apps, schema_editor):
    Group.objects.filter(name='window').delete()
    Group.objects.filter(name='access').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0003_remove_ticketwindow_users'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
