# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_auto_20160712_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketwindow',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='ticketwindowcashmovement',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='windows.TicketWindow', verbose_name='window'),
        ),
        migrations.AlterField(
            model_name='ticketwindowsale',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tickets.MultiPurchase', verbose_name='multipurchase'),
        ),
        migrations.AlterField(
            model_name='ticketwindowsale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='ticketwindowsale',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='windows.TicketWindow', verbose_name='window'),
        ),
    ]
