# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0007_auto_20160712_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='code',
            field=models.CharField(default='TAQ', help_text='code to show in tickets', max_length=5, verbose_name='code'),
            preserve_default=False,
        ),
    ]
