# Generated by Django 2.2.24 on 2021-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210903_1044'),
        ('windows', '0009_ticketwindow_number_of_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='templates',
            field=models.ManyToManyField(to='events.TicketTemplate'),
        ),
    ]
