# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0010_auto_20160920_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketwindow',
            name='cash',
            field=models.FloatField(default=0, verbose_name='cash in the ticket window'),
        ),
    ]
