# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0012_auto_20160927_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketwindowcashmovement',
            options={'ordering': ['-id'], 'verbose_name': 'ticket window cash movement', 'verbose_name_plural': 'ticket window cash movements'},
        ),
    ]
