# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('windows', '0014_auto_20161024_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketwindow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
